# Site settings
title: Sysadmin 4 lyfe
email: therealpatrobinson@gmail.com
description: >
  This blog covers various issues I encounter
  and the (sometimes creative) solutions I apply.
baseurl: ""
url: "http://patrobinson.github.io" # the base hostname & protocol for your site
twitter_username: DrNemski
github_username:  patrobinson
about_me: >
  I'm a Development Operations Engineer (i.e. Systems Administrator) with experience in Unix, Puppet, VMware and Programming in Bash, Perl and Ruby. My ramblings are usually loosely related to these topics. I also enjoy dabling in whatever new technology I see as relevant. I try not to talk about the latest "fad" in Technology, unless it's to explain how it relates to day-to-day workings of a sysadmin. I also try not to target to the lowest common denominator.

# Build settings
markdown: kramdown

timezone: "Australia/Sydney"

google_analytics_id: 'UA-46810553-2'

# theme settings
header-img: img/home-bg.jpg
highlighter: rouge
permalink: pretty
paginate: 5
gems:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap
