# Site settings
title: Sysadmin 4 lyfe
email: therealpatrobinson@gmail.com
description: >
  I am a System Administrator/DevOps Engineer with experience in automation,
  Unix systems and programming. This blog covers various issues I encounter
  and the (sometimes creative) solutions I apply.
baseurl: ""
url: "http://nemski.thematrix.local" # the base hostname & protocol for your site
twitter_username: DrNemski
github_username:  nemski

# Build settings
markdown: kramdown

timezone: "Australia/Sydney"
